[dash_textarea_autocomplete_resources]
git-tree-sha1 = "4cd536223251615d2ae01a3463bc56d2342c6326"

    [[dash_textarea_autocomplete_resources.download]]
    sha256 = "53df754a9b137041671a11d1138ea4dcb20bf5831ea7aa33d3c679f41cc6be2e"
    url = "https://unpkg.com/dash-textarea-autocomplete@1.3.2/deps/deps.tar.gz"
