[dash_textarea_autocomplete_resources]
git-tree-sha1 = "40556a4d143e9e1b25db0e0f434e9415989b3385"

    [[dash_textarea_autocomplete_resources.download]]
    sha256 = "b24ab87c857bca449e269b74cdad8a36e32b9fca633a12c2ab6444ff5bfee94e"
    url = "https://unpkg.com/dash-textarea-autocomplete@1.2.1/deps/deps.tar.gz"
