[dash_textarea_autocomplete_resources]
git-tree-sha1 = "40556a4d143e9e1b25db0e0f434e9415989b3385"

    [[dash_textarea_autocomplete_resources.download]]
    sha256 = "cb8d647e266bd7df24c08346d498b42bd246bef561d3e22304450c2c2603c6f1"
    url = "https://unpkg.com/dash-textarea-autocomplete@1.2.1/deps/deps.tar.gz"
