[dash_textarea_autocomplete_resources]
git-tree-sha1 = "4cd536223251615d2ae01a3463bc56d2342c6326"

    [[dash_textarea_autocomplete_resources.download]]
    sha256 = "605cb911677d1df4fe37fc45376cb7ea9875008ceea24b500872662ea698ba7f"
    url = "https://unpkg.com/dash-textarea-autocomplete@1.3.1/deps/deps.tar.gz"
