
name = "DashTextareaAutocomplete"
uuid = "1b08a953-4be3-4667-9a23-5aadec407a69"
authors = ["Etienne Tetreault-Pinard <info@etpinard.xyz>"]
version = "1.3.0"

[deps]
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.3"
Dash = "0.1.3, 1.0"
RelocatableFolders = "0.1"
