
name = "DashTextareaAutocomplete"
uuid = "1b08a953-4be3-4667-9a23-5aadec407a69"
authors = ["Etienne Tetreault-Pinard <info@etpinard.xyz>"]
version = "1.3.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.3"
Dash = "0.1.3, 1.0"
