name: Tests

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build component
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install JavaScript dependencies
        run: npm ci
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt
      - name: Install Python test dependencies
        run: python -m pip install -r tests/requirements.txt
      - name: Build dash-textarea-autocomplete
        run: npm run build
      - name: Test
        run: pytest tests
